### ISSUE TITLE
Zoning on River

### ISSUE THREAD

**Issue by gregmacfarlane** [pbsag/tlumip#51]
The reference scenario shows a substantial density increase (in both population and employment) along the rivers in Portland. This is coupled with a density *decrease* in presently developed areas in Portland. The zoning and allocation rules need to be verified.

**Comment by bettinardi** [comment]
I have done some initial review.  I would not have used the word "substantial" in the issue above.  We did all agree that there were increases, but I left the discussion that this was a potential issue, as opposed to a known issue, which the word "substantial" suggests to me is a known issue that needs to be dealt with.

In my poking around I started with zone 927, which represents the West side of Hayden island which currently has almost no development on it, if any - 
https://www.google.com/maps/place/Hayden+Island/@45.6228837,-122.7321338,13z/data=!3m1!4b1!4m5!3m4!1s0x5495a893010b732f:0xe0cd215d97ab7887!8m2!3d45.6223771!4d-122.7017681?hl=en

In the states zoning coverage layer the vast majority of that zone is coded as FF20 - Mixed Farm-Forest 20.  This is a generic code and SWIM is allowed to build RRMH, RRSFD, Light Industry and Warehouse on that land.  There is - 75,634,612 sqft of FF20 land in zone 927.  In the FAR file, one can see that all four floorspace types can only build at a ratio of 1/2000 on FF20.  
https://github.com/pbsag/tlumip/blob/master/root/scenario/inputs/t0/far.csv
Meaning that there ~38k sqft of develop-able space in zone 927.

All of that seems fine, but there are issues with zone 927:
1. For whatever reason water was not subtracted from zone 927 and the other 3 Hayden island zones, but it does seem correctly subtracted from the rest of the Columbia river.  So Hayden island does have more build able land than it should, but nothing that should be rocking the model to it's core.
2. SWIM zones were not drawn / generated particularly well, that means that there is a lot of overlap with adjacent zone's zoning coverage.  This allows for slivers of higher density zoning to creep into zone 927.  However, none of the other coverage are of any significant size. 
3.  My review did find that 2 sqft of high density space was in 927 - "Mixed-Use Com. & Res. V.High".  The 2 sqft seems to be from some sort of sliver line work that should not exist in the area, just a messiness in the data that is probably going to have to be excepted.

This review makes me think that we could build some rules into this to help clean it up a little.  We could say that if a zone has less than, say 5%, of a given zoning type - to drop those slivers of coverage and distribute the square footage to the more representative coverage in the zone.  However, a global change like this would likely impact PECAS calibration.

I think at a minimum we could go in and subtract the water space and review more closely the 4 Hayden island zones, to get those cleaned-up.

I looked up and down the rivers from 927 - water seems to be correctly subtracted.
@gregmacfarlane - please provide additional zones where you are seeing "substantial" growth.  Like for 927 I think we saw something like 2 houses balloon to 2000.  If you are seeing other zones with that type of growth (outside of Hayden island (927,911,961,909), please let me know and I will dig in and get some detailed answers.  Otherwise, the zoning looks correct, and I would point back to a surplus of land in general and some sort of price calibration issues along the river zones, to combat the lots of potential space versus lack of development due to other issues.  For example - the river is very expensive to develop because basically every plot along Portland's rivers is a super fund sight.  They all need massive government subsidies before developers come in to clean them up.  This is probably the real reason that the river is booming.  The hidden cost of cleaning up toxic land is not represented in SWIM.

**Comment by gregmacfarlane** [comment]
That all makes lots of sense, and I agree that it is probably a systemic issue (like we're not capturing the costs of developing on the river) more than a data one. But we need to be sure that the water and wetland areas are removed from the available space database.

**Comment by gregmacfarlane** [comment]
Here are some zones that I find particularly egregious, and I think we should review:

| azone| 20_hh| 20_pop| 35_hh| 35_pop| 50_hh| 50_pop|
|-----:|-----:|------:|-----:|------:|-----:|------:|
|   624|    61|    153|   321|    595|   673|   1119|
|   678|     5|      8|   254|    408|   606|    956|
|   902|     1|      1|    18|     35|    42|     75|
|   903|     0|     NA|    21|     36|    39|     70|
|   925|     2|      3|    48|    126|   113|    294|
|   927|     3|      9|    61|    145|   135|    333|
|   959|     1|      3|    15|     28|    31|     61|

Here's how you can build this table:
```r
library(swimr)
library(dplyr)
library(tidyr)

river_zones <- c(925, 927, 959, 902, 903, 959, 624, 678)

db <- src_sqlite("../data/ALD_quartCons.db")
tbl(db, "AZONE") %>% 
  select(azone = AZONE, pop = POPULATION, hh = TOTALHHS, TSTEP) %>% 
  filter(TSTEP %in% c("20", "35", "50")) %>% 
  filter(azone %in% river_zones) %>%
  collect() %>%
  gather(variable, count, pop:hh) %>%
  unite(var, TSTEP, variable) %>%
  spread(var, count) %>%
  knitr::kable()
```

**Comment by bettinardi** [comment]
Zone 624 - 75% water, ~20M sqft of viable land to build.
Zone 678 - 25% water, ~34M sqft of viable land to build, currently has the troutdale airport (so SWIM is going to have a hard time with that one).
Zone 902 - 55% water, ~36M sqft of viable land to build, currently has one of the larger shopping complexes on it in the Portland area - it has the only Oregon IKEA.
Zone 903 - 0% water (land locked), ~13M sqft of viable land to build, next to the airport - a tricky one for SWIM to get right.
Zone 925 - 25% water, ~100M sqft of viable land to build - currently the port of Portland, right next to residential space - going to be hard for SWIM.
Zone 927 - hayden island - already noted that there was an issue (water not being accounted for), details are discussed in comments above.
Zone 959 - ~0% water, The Portland International Raceway, again - SWIM can't be expected to get these right, they are too specialized..

In general, with the exception of Hayden Island (927, 909, 911, 961), I don't see any real issue.  SWIM is working at a larger level than this level of detail.  I would suggest either aggregating up to beta zones for these types of maps, or the better option would be the one that John and I pushed for - to ditch choropleths (which are always problematic) and go to a dot density type of map.

**Comment by gregmacfarlane** [comment]
Well, the problems with chloropleths are attenuated by higher levels of aggregation. I think that dot density plots can be useful, but they have weaknesses (like showing negative growth; we never would have seen Vancouver emptying with dot densities). I'll see what we can do by the end of TLUMIP5. 

To the point, if you don't see a problem here, then I will close the issue.

**Comment by gregmacfarlane** [comment]
That said, if there is an airport or dock in the zone, why do we not take it out like we do water?

**Comment by bettinardi** [comment]
That would require a level of manual cleaning that would be unjustified - at least in my mind.
You could say the same thing about our universities, or the capital, or the Oregon gardens, or the Pendleton round-up, the international race way, the rose garden...  We don't have a layer of "all things that SWIM shouldn't build on".

It would take a large effort,; and whose to say that these "permanent" land uses hold into the future.  This is not the role of SWIM.  This kind of land use detail is meant for urban models.  At SWIM we follow a "good from far, but far from good" type of logic.

**Comment by bettinardi** [comment]
Remember we have a generalized transit approach - consider this generalized land use.
