### ISSUE TITLE
Update SWIM for Visum 16

### ISSUE THREAD

**Issue by bettinardi** [pbsag/tlumip#62]
Some swim_small test have been done and seem to verify that SWIM works perfectly fine with Visum 16.  The change to 16 is in the properties file, so no issue needs to be created to allow SWIM to work in Visum 16.  However in Visum 16, the parameter files were changed from complied data files to an open xml format.  It would be ideal to switch all parameters files to xml.  Farther down the line, we can shrink the xml files so that the code can potentially update xml files as needed.

@bstabler.  We also need to change the setup of the select link process so that it uses the Visum version specified in the properties file, instead of the install in the registry.

**Comment by bstabler** [comment]
In order to change the setup of the select link process so that it uses the Visum version specified in the properties file, instead of the install in the registry, we'll need to revise the Java code and re-compile the jar since the overall Java-based model runner passes the variable to the select link Python script as a command line argument.

**Comment by bettinardi** [comment]
Got it.  So we probably won't cover that next week.  Let's see how far we get with Visum 16ing SWIM next week.  Then we can end the meeting next Tuesday with closing this issue and starting a new issue for TLUMIP 6 of the other items related to Visum 16 that we want to accomplish (if any).

**Comment by bettinardi** [comment]
All done [hand dusting]
